apiVersion: v1
kind: Namespace
metadata:
  name: oficina-staging
  labels:
    oficina.io/environment: staging
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
