apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-account.yaml
  - deployer-rbac.yaml
  - secret-provider.yaml
  - workload.yaml
  - network-policies.yaml
labels:
  - pairs:
      app.kubernetes.io/part-of: oficina
      app.kubernetes.io/managed-by: oficina-k8s-infra
    includeSelectors: true
