apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: oficina-runtime-secrets
spec:
  provider: aws
  secretObjects:
    - secretName: oficina-runtime-secrets
      type: Opaque
      data:
        - objectName: db_username
          key: db_username
        - objectName: db_password
          key: db_password
  parameters:
    region: us-east-1
    objects: |
      - objectName: "${APP_SECRET_ARN}"
        objectType: "secretsmanager"
        jmesPath:
          - path: "username"
            objectAlias: "db_username"
          - path: "password"
            objectAlias: "db_password"
